### ISSUE TITLE
[tracker] revamp the spec

### ISSUE THREAD

**Issue by vbatts** [opencontainers/distribution-spec#126]
Tracker for reorganizing the spec (started from #125 discussion)
As of commit 38956df5d3957ab35785c608f8cf715584f08a8d:
* [x] TOC
* [x] murder the changes.md file
* [x] introduction
* [x] historical context (moved to `./history.md`)
* [x] terms / glossary
* [x] conformance categories
* [x] endpoints (nitty gritty)
* [x] add appendix
* [x] describe relationship to OCI images
* [ ] uses cases should link to workflows
* [x] "image" -> "artifact"
* [x] remove rules/requirements specific to images (blobs before configs etc)
* [ ] finalize HTTP status codes
* [ ] address https://github.com/opencontainers/distribution-spec/issues/183

the idea being that these are mergable chunks of PRs, 
For readers of the spec, the spec is organized according to the nature of the reviewers (general information, slightly more detail, and registry/tool implementors).

**Comment by jdolitsky** [comment]
For changes related to spec.md, does it make sense for us to open up a new staging branch like "rewrite" ? Then once all these boxes are checked, do a big PR from rewrrite->master with a bunch of changes that the maintainers have already agreed upon?

The alternative I see is making a new glossary.md etc on master which would later be deleted. Thoughts?

**Comment by mikebrow** [comment]
remove the ## changes section https://github.com/opencontainers/distribution-spec/blame/master/spec.md#L131

**Comment by jdolitsky** [comment]
Resolved by #206
