### ISSUE TITLE
[tracker] mini spec updates for 1.0

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/distribution-spec#163]
Related to https://github.com/opencontainers/distribution-spec/issues/126

This ticket is simply to track open pull requests for mini spec updates related to reorganization for a 1.0 release.

PRs (checkbox checked if merged):

- [x] 1. remove reorg comment (#158)
- [x] 2. new table of contents  (#159)
- [x] 3. fill in overview section (#160)
- [x] 4. fill in definitions section (#161)
- [x] 5. fill in conformance section (sans workflows) (#162)
- [x] 6. describe pull workflow (#166)
- [x] 7. describe push workflow (#167)
- [x] 8. describe content discovery workflow (#168)
- [x] 9. describe content management workflow (#169)
- [x] 10. add endpoint table (#173)
- [x] 11. error codes (#174)
- [x] 12. add references and links to endpoint IDs (#175)
- [x] 13. update definitions (#177)
- [x] 14. not-so-mini update (https://github.com/opencontainers/distribution-spec/pull/178)

**Comment by jdolitsky** [comment]
closing, remaining tasks outlined in https://github.com/opencontainers/distribution-spec/issues/126
